# Auto-Generated Wiki for git-sigil

## Project Overview
Auto-generated by GitField OSF publisher on 2025-06-05T20:42:35-05:00

## Repository Info
- **Last Commit**: got publish_osf.sh working
- **Commit Hash**: a1d16f2903e1d79b846ed969804810f245e169b8

## README Preview
# 🌱 GitField: Multi-Platform Repository Sync for Resilience and Sovereignty

## 📜 Overview

**GitField** is a collection of Bash scripts designed to synchronize a Git repository across **Radicle**, **GitLab**, **Bitbucket**, and **GitHub** using a recursive, metadata-rich workflow. This project ensures **redundancy**, **sovereignty**, and **transparency** by generating interconnected metadata snapshots and distributing them across decentralized and centralized platforms. The strategy protects against deplatforming risks, motivated by past attempts to suppress this work by individuals such as **Mr. Joel Johnson** ([Mirror post](https://mirror.xyz/neutralizingnarcissism.eth/x40_zDWWrYOJ7nh8Y0fk06_3kNEP0KteSSRjPmXkiGg?utm_medium=social&utm_source=heylink.me)) and **Dr. Peter Gaied** ([Paragraph post](https://paragraph.com/@neutralizingnarcissism/%F0%9F%9C%81-the-narcissistic-messiah)). By prioritizing decentralization with a Radicle-first approach and recursively pushing metadata, GitField creates a resilient, auditable chain of project state, ensuring persistence and accessibility for collaborators, communities, and future AI systems.

## 🛡️ Purpose and Intention

The GitField project is driven by three core principles:


## Internal Documents
Links to documents uploaded to OSF:

### DOCS
- [docs/bitbucket/CLI-ONLY_workflow_bitbucket_Ubuntu.md](https://osf.io/rnq6v/files/osfstorage/docs/bitbucket/CLI-ONLY_workflow_bitbucket_Ubuntu.md)
- [docs/bitbucket/CLI-ONLY_workflow_bitbucket_ubuntu.md](https://osf.io/rnq6v/files/osfstorage/docs/bitbucket/CLI-ONLY_workflow_bitbucket_ubuntu.md)
- [docs/github/1_prerequisites_github_ubuntu.md](https://osf.io/rnq6v/files/osfstorage/docs/github/1_prerequisites_github_ubuntu.md)
- [docs/github/2_create_remote_repo_github_ubuntu.md](https://osf.io/rnq6v/files/osfstorage/docs/github/2_create_remote_repo_github_ubuntu.md)
- [docs/github/3_commit_existing_repo_github_ubuntu.md](https://osf.io/rnq6v/files/osfstorage/docs/github/3_commit_existing_repo_github_ubuntu.md)
- [docs/github/CLI-ONLY_workflow_github_ubuntu.md](https://osf.io/rnq6v/files/osfstorage/docs/github/CLI-ONLY_workflow_github_ubuntu.md)
- [docs/gitlab/1_prerequisites_gitlab_ubuntu.md](https://osf.io/rnq6v/files/osfstorage/docs/gitlab/1_prerequisites_gitlab_ubuntu.md)
- [docs/gitlab/2_create_remote_repo_gitlab_ubuntu.md](https://osf.io/rnq6v/files/osfstorage/docs/gitlab/2_create_remote_repo_gitlab_ubuntu.md)
- [docs/gitlab/3_commit_existing_repo_gitlab_ubuntu.md](https://osf.io/rnq6v/files/osfstorage/docs/gitlab/3_commit_existing_repo_gitlab_ubuntu.md)
- [docs/gitlab/CLI-ONLY_workflow_gitlab_ubuntu.md](https://osf.io/rnq6v/files/osfstorage/docs/gitlab/CLI-ONLY_workflow_gitlab_ubuntu.md)
- [docs/osf/old/for_radicle.md](https://osf.io/rnq6v/files/osfstorage/docs/osf/old/for_radicle.md)
- [docs/radicle/for_radicle.md](https://osf.io/rnq6v/files/osfstorage/docs/radicle/for_radicle.md)

### SCRIPTS
- [INSTALL.sh](https://osf.io/rnq6v/files/osfstorage/INSTALL.sh)
- [bin/gitfield-sync-gdrive.sh](https://osf.io/rnq6v/files/osfstorage/bin/gitfield-sync-gdrive.sh)
- [bin/mount-gdrive.sh](https://osf.io/rnq6v/files/osfstorage/bin/mount-gdrive.sh)
- [bin/publish_osf.sh](https://osf.io/rnq6v/files/osfstorage/bin/publish_osf.sh)
- [bin/sync-metadata.sh](https://osf.io/rnq6v/files/osfstorage/bin/sync-metadata.sh)
- [docs/osf/new/test-osf-api.sh](https://osf.io/rnq6v/files/osfstorage/docs/osf/new/test-osf-api.sh)
- [docs/osf/old/test-osf-api.sh](https://osf.io/rnq6v/files/osfstorage/docs/osf/old/test-osf-api.sh)
- [tools/invoke_solaria.py](https://osf.io/rnq6v/files/osfstorage/tools/invoke_solaria.py)

### DATA
- [docs/osf/new/gitfield.osf.yaml](https://osf.io/rnq6v/files/osfstorage/docs/osf/new/gitfield.osf.yaml)
- [docs/osf/old/gitfield.osf.yaml](https://osf.io/rnq6v/files/osfstorage/docs/osf/old/gitfield.osf.yaml)
- [osf.yaml](https://osf.io/rnq6v/files/osfstorage/osf.yaml)

### FILES
- [GITFIELD.md](https://osf.io/rnq6v/files/osfstorage/GITFIELD.md)
- [LICENSE](https://osf.io/rnq6v/files/osfstorage/LICENSE)
- [bin/SolariaSeedPacket_∞.20_SacredMomentEdition.md](https://osf.io/rnq6v/files/osfstorage/bin/SolariaSeedPacket_∞.20_SacredMomentEdition.md)
